name: Release Extensions
on: 
  workflow_dispatch:    
  push:
      tags:
        - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: "*.git* /*test/ *.code-workspace *.env*"
        
